-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20
NDefines.NGame.START_DATE = "2280.1.1"
NDefines.NGame.END_DATE = "3000.1.1"
NDefines.NGame.MAX_RANDOM_NEW_WORLD = "3000.1.1"
NDefines.NGame.GREAT_POWER_FRENZY_START = "3000.1.1"
NDefines.NGame.AGE_USHER_IN_TIME = 1

NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 250
NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 500
NDefines.NDiplomacy.NUM_POSSIBLE_RIVALS = 1
NDefines.NDiplomacy.TRUCE_YEARS = 2 								-- _DDEF_TRUCE_YEARS_; Years of Truce
NDefines.NDiplomacy.SCALED_TRUCE_YEARS = 3						-- Additional years of truce based on % of warscore taken in war (100% warscore = full scaled truce years)
NDefines.NDiplomacy.FABRICATE_CLAIM_COST = 10
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12			-- Before this many months have passed in the war, you cannot gain 100% warscore by just occupying the warleader
NDefines.NDiplomacy.THREATEN_WAR_TRUCE_YEARS = 2					-- Length of truce imposed by Threaten War.
NDefines.NDiplomacy.FORCE_BREAK_ALLIANCE_TRUCE_YEARS = 2			-- Length of truce imposed by Break Alliance.
NDefines.NDiplomacy.AUTODIPLO_TARGET_COALITION_IMPROVECAP = 80 -- Changed so this actually pushes them into the won't join level
NDefines.NDiplomacy.IMPERIAL_REALM_WAR_IA_COST = 10.0				-- How much IA the Realm War CB costs.
NDefines.NCountry.EXPLOIT_ADM_INCOME = 120	-- months of income
NDefines.NCountry.EXPLOIT_DIP_SAILORS = 12
NDefines.NCountry.EXPLOIT_MIL_MANPOWER = 12
NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 0
NDefines.NCountry.SIBERIAN_FRONTIER_DAILY_BASE = 1		-- monthly..
NDefines.NCountry.SIBERIAN_FRONTIER_DAILY_RANGE = 5
NDefines.NCountry.SPLENDOR_ABILITY_COST = 1000
NDefines.NCountry.ABDICATE_LEGITIMACY_HIT = -50
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -100
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -100
NDefines.NCountry.NEW_HEIR_PRESTIGE_HIT = -50
NDefines.NCountry.NEW_HEIR_LEGITIMACY_HIT = -50
NDefines.NCountry.NEW_HEIR_CLAIM_RANDOM_FACTOR = 50
NDefines.NCountry.EMBRACE_INSTITUTION_COST = 3				-- 2.5 per development (autonomy modified)
NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 1.0		-- non accepted culture
NDefines.NCountry.OVERSEAS_CLIENT_STATES = 1					-- Allow overseas client states?
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 32.0 	-- Minimum of crownland when distributing land at start
NDefines.NCountry.ESTATE_AGENDA_ABOUT_TO_EXPIRE_WARNING = 365 -- How many days it should start warning for agenda about to expire
NDefines.NCountry.HRE_MAX_RANK = 3							-- for members
NDefines.NCountry.HRE_MAX_RANK_ELECTOR = 3					-- for electors
NDefines.NCountry.ALLOW_FEMALE_GENERALS = 1
NDefines.NCountry.FEMALE_ADVISOR_CHANCE = 0						-- If Women in History is enabled, chance of an advisor (or general if permitted) spawning as female
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 1.0
NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 20			-- Must have this level of dip tech to circumnavigate the globe
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_1 = 1516			-- Provinces for circumnavigation (coast of gambia)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_2 = 1530			-- Provinces for circumnavigation (magellan strait)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_3 = 1554			-- Provinces for circumnavigation (hawaii sea)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_4 = 1667			-- Provinces for circumnavigation (hawaii sea)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_5 = 1690			-- Provinces for circumnavigation (hawaii sea)
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_6 = 1716			-- Provinces for circumnavigation (cape of good hope)
NDefines.NCountry.ADVISOR_COST_INCREASE_PER_YEAR = 0.01			-- yearly increase in price in percent,
NDefines.NCountry.MAXIMUM_ADVISOR_SKILL = 10						-- Maximum advisor skill reachable through promotion
NDefines.NCountry.PROMOTE_COST_MONTHS_ADVISOR_SALARY = 120.0		-- Promote advisor cost in monthly salaries
NDefines.NCountry.CULTURE_MIN_DEVELOPMENT_TO_PROMOTE = 1		-- Minimum development required to promote the culture.
NDefines.NCountry.MONARCH_DEATH = 0 								-- _CDEF_MONARCH_DEATH_
NDefines.NCountry.MONARCH_DEATH_MIN_CHANCE_MODIFIER = 0.0		-- Minimum death chance modifier
NDefines.NCountry.HEIR_DEATH = 0 								-- _CDEF_HEIR_DEATH_	(Only applies for heirs older than 20, and the chance increases with age.)
NDefines.NCountry.PS_MOVE_CAPITAL = 100
NDefines.NCountry.PS_MOVE_CAPITAL_DISTANCE_CAP = 100				-- How much this penalty is allowed to cost in Adm.
NDefines.NCountry.PS_MOVE_TRADE_PORT = 100
NDefines.NCountry.PS_CHANGE_CULTURE = 5
NDefines.NCountry.PS_HARSH_TREATMENT_COST = 100					-- Max cost for harsh treatment (scales to revolt size)
NDefines.NCountry.PS_ESTABLISH_SIBERIAN_FRONTIER = 100
NDefines.NCountry.STRENGTHEN_GOVERNMENT_REPUBLICAN_TRADITION = 10
NDefines.NCountry.CORE_HAD_CLAIM = 0.25							-- Impacts MODIFIER_CORE_CREATION
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_TECHNOLOGY = 9999		-- Years until discoveries spread within technology group
NDefines.NCountry.PROVINCE_DISCOVERY_YEARS_RELIGION = 9999		-- Years until discoveries spread with religion
NDefines.NCountry.CORE_LOSE = -1 								-- how many years until a core is lost.
NDefines.NCountry.CORE_LOSE_CULTURE_GROUP = -1					-- how many years until a core in a country's culture group is lost.
NDefines.NCountry.YEARS_PER_EXTRA_PERSONALITY = 10				-- Number of years between new personalities after first one.
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 2					-- How many months it will take to change culture in a province, per development.
NDefines.NCountry.STARTING_ARMY_SIZE = 0.5						-- Percentage of force limit
NDefines.NCountry.REVOLT_SIZE_DEVELOPMENT_MULTIPLIER = 0.3		-- Multiplied with the province's development
NDefines.NCountry.REVOLT_SIZE_BASE = 4
NDefines.NCountry.MIGRATION_BOOST = 10							-- How many points given when migrating.
NDefines.NCountry.MIGRATION_COOLDOWN = 12						-- How many months until next migration is possible.
NDefines.NCountry.MIGRATION_DEPLETION_TIME = 365				    -- How many days a province needs to recover from migrants
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.05 			-- % each tech increases it.
NDefines.NEconomy.LAND_TECH_MERC_MAINTENANCE_IMPACT = 0.05 			-- % each tech increases it.
NDefines.NMilitary.FORT_PER_DEV_RATIO = 100						-- 1 non-obsolete maintained fort per this amount of development = +1 AT
NDefines.NMilitary.ARMY_ATTRITION_AT_SEA = 1						-- How many percent attrition units take while loaded onto ships traveling open sea
NDefines.NMilitary.INFANTRY_SPEED = 1.0 							-- _MDEF_INFANTRY_SPEED = 10,
NDefines.NMilitary.CAVALRY_SPEED = 1.0 							-- _MDEF_CAVALRY_SPEED = 10,
NDefines.NMilitary.ARTILLERY_SPEED = 1.0 							-- _MDEF_ARTILLERY_SPEED = 10,
NDefines.NMilitary.FORTRESS_COST = 0.2							-- base fort cost
NDefines.NMilitary.INFANTRY_TIME = 90 							-- _MDEF_INFANTRY_TIME = 10,
NDefines.NMilitary.ARTILLERY_TIME = 90 							-- _MDEF_ARTILLERY_TIME = 10,
NDefines.NMilitary.HEAVY_SHIP_TIME = 120 							-- _MDEF_HEAVY_SHIP_TIME = 10,
NDefines.NMilitary.LIGHT_SHIP_TIME = 90 							-- _MDEF_LIGHT_SHIP_TIME = 10,
NDefines.NMilitary.GALLEY_TIME = 90 								-- _MDEF_GALLEY_TIME = 10,
NDefines.NMilitary.TRANSPORT_TIME = 90 							-- _MDEF_TRANSPORT_TIME = 10,
NDefines.NMilitary.BASE_COMBAT_WIDTH = 20.0						-- _MDEF_BASE_COMBAT_WIDTH_
NDefines.NMilitary.MAX_COMBAT_WIDTH = 30
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 60					-- maximum amount to get from a battles .
NDefines.NMilitary.MIN_RECRUIT_TIME_MODIFIER = 0.1					-- Recruit time cannot be lower than this * base
NDefines.NMilitary.MERCENARY_COMPANY_MIN_REGIMENTS = 5			-- Minimum regiments
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 20			-- Maximum regiments
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 0.9 --AI wants this advantage to enter battles typically. (There are some exceptions, e.g. offensives.)
NDefines.NAI.EDICT_VALUE_THRESHOLD = 70 -- The higher this value, the less the AI will use Edicts
NDefines.NAI.WANT_TRIBUTARY_LOST_MANDATE = 1 -- How important it is for Celestial Emperor to make tributaries out of neighbors.
NDefines.NAI.DEVELOP_IN_SUBJECTS_PREFERENCE = 0.55 -- At 1, AI likes developing subjects approximately the same as its own provinces (more or less depending on their Liberty Desire).
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_NEIGHBORS = 0 --If set to 1, AI will only send Condottieri to neighbors, regardless of access.
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_DISABLE_VERSUS_PLAYER_ENEMIES = 1 --If set to 1, AI will try avoid sending Condottieri having to fight against human player enemies.
NDefines.NAI.FORT_MAINTENANCE_CHEAT = 1 -- Set to 0 to disable AI fort maintenance cheating. Warning: Will make AI suck.
NDefines.NAI.AGGRESSIVENESS = 1000 -- Base chance (out of 10000) of AI being willing to start a war each diplomatic tick (~1.5 times a month)
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 2000 -- Added to aggressiveness if the war is against a weak or particularily hated enemy
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 0 -- AI must have at least this many monthly deficits of savings to be willing to deficit spend
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 6 -- Same as DEFICIT_SPENDING_MIN_MONTHS, but during peacetime, no rebels and no war exhaustion
NDefines.NAI.ARTILLERY_FRACTION = 0.4 	-- Ratio of artillery to infantry AI will build
NDefines.NAI.TRANSPORT_FRACTION = 0.4 -- Max fraction of naval forcelimit that should be transports
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.01 -- AI will reserve this amount of their surplus for long-term savings
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 1 -- The higher this number is, the less willing the AI will be to exceed forcelimits
NDefines.NAI.DESIRED_DEFICIT = 0.4 -- AI will try to spend this fraction of their money above their target for long term savings.
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.1 -- AI will aim for having at least this fraction of their income as additional surplus when they need buildings
NDefines.NAI.MAX_SAVINGS = 30 -- AI will keep a maximum of this * their monthly income in long-term savings
NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.35 -- AI will spend a maximum of this fraction of monthly income on advisor maintenance
NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 0.2 -- AI will spend a maximum of this fraction of monthly income on rooting out corruption
NDefines.NAI.ARMY_BUDGET_FRACTION = 2.0 -- AI will spend a maximum of this fraction of monthly income on army maintenance (based off wartime costs)
NDefines.NAI.REGIMENTS_PER_GENERAL = 30 -- AI will want one general for every this number of regiments (will not exceed free leader pool)
NDefines.NAI.MIN_SHIPS_FOR_ADMIRAL = 30 -- The minimum navy size for the AI to bother with an admiral
NDefines.NAI.REGIMENTS_FOR_CONQUISTADOR = 10 --The maximum size of army AI will use for an exploring conquistador.
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 350 -- Beyond this range, AI is less interested in conquest of provinces
NDefines.NAI.FORCE_MARCH_MIN_SIZE = 15 -- AI will not force march units with less regiments than this
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 1000 -- AI will not save up for a building that costs more than their monthly income * this, if there are cheaper alternatives
NDefines.NAI.PURSUE_DISTANCE = 600 -- AI will not pursue armies retreating to a province further away than this
NDefines.NAI.CALL_IN_ALLIES_POWER_RATIO = 6.0 -- AI will only call in allies in an offensive war if their military power ratio to the enemy is less than this
NDefines.NAI.DEVELOPMENT_CAP_BASE = 30	-- AI will not develop provinces that have more development than this or DEVELOPMENT_CAP_MULT*original development (whichever is bigger)
NDefines.NAI.DEVELOPMENT_CAP_MULT = 5
NDefines.NAI.PEACE_TIME_MONTHS = 12 -- Months of additional AI stubbornness in a war
NDefines.NAI.PEACE_TIME_MAX_MONTHS = 24 -- Max months applied to time factor in a war
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 2.0 -- AI willingness to peace based on war exhaustion
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 5.0 -- Additional AI willingness to peace based on war exhaustion above the high threshold
NDefines.NAI.PEACE_WARGOAL_FACTOR = 20 -- AI unwillingness to peace based on holding the wargoal
NDefines.NAI.PEACE_MILITARY_STRENGTH_FACTOR = 50 -- AI unwillingness to peace based on manpower & forcelimits
NDefines.NAI.PEACE_OTHER_WAR_FORCE_BALANCE_MULT = 0.25 -- Multiplies the force balance of other countries who are involved in a different war with either side
NDefines.NAI.PEACE_DESPERATION_FACTOR = 100 -- AI willingness to peace based on desperation from occupied homelands
NDefines.NAI.PEACE_REBELS_FACTOR = 50 -- AI willingness to peace based on number of revolts in their provinces
NDefines.NAI.PEACE_COALITION_FACTOR = 10 -- AI unwillingness to peace based on being in a coalition war
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 10	-- How much AI wants peace based on having call for peace
NDefines.NAI.PEACE_TERMS_VASSAL_BASE_MULT = 5.0 -- NOT only applied if the AI has vassalize priority
NDefines.NAI.PEACE_TERMS_TRADE_POWER_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_REVOKE_CORES_BASE_MULT = 0.1
NDefines.NAI.PEACE_TERMS_REVOKE_REFORM_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_RETURN_CORES_BASE_MULT = 0.5
NDefines.NAI.PEACE_TERMS_ANNUL_TREATIES_BASE_MULT = 0.25
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 600							-- How much the AI values having much development in accepted cultures.
NDefines.NAI.MARRIAGE_DESIRE_TOO_MANY_RELATIONS = -20				-- AI desire/acceptance for royal marriange when it has or will get too many relations. Multiplies with number of relations above limit.
NDefines.NAI.GUARANTEE_DESIRE_TOO_MANY_RELATIONS = -20				-- AI desire for guaranteeing when it has or will get too many relations. Multiplies with number of relations above limit.
NDefines.NAI.INVADING_BRAVERY = 1.5									-- If (defender strength) / (invader strength) > INVADING_BRAVERY, the AI won't attempt a naval invasion
NDefines.NAI.DRILL_BONUS_WAR_READINESS = 2							-- Bonus for war readiness of drilled units
NDefines.NAI.DRILLING_DEBT_SURPLUS_RATIO_THRESHOLD = 0.1				-- AI will only consider drilling if Surplus / Debt ratio is above
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 48							-- AI will not promote advisors above this age
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.05					-- AI will only assign armies larger that this to a region
NDefines.NAI.TRADE_COMPANY_INVESTMENT_COST_THRESHOLD = 2.0				-- How many times the cost of the investment must be in the treasury to consider buying it
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 20					-- Influence on assimilation interest from number of provinces left to conquer
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT = 100.0							-- Army <-> province distance impact on province evaluation
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 100.0							-- Border <-> province distance impact on province evaluation
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.01							-- AI will try to defend provinces under threat worth more than this percentage of total development
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 6.5				-- Homeland priorization when assigning armies to regions (only applied when actually threatened)
NDefines.NAI.MISSIONARY_MAINTENANCE_SHARE = 0.4							-- The most an AI will spend of its income on a missionary
NDefines.NGraphics.SHIELD_GLOW_RANGE = 0.0						-- Set to 0 to disable Great Power shield glow, set to 1 for epileptic seizure.
NDefines.NGraphics.MAX_NUM_YEAR_OF_TRUCE_FOR_MAPMODE = 5
NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 10						-- The number of spawned centers of reformation wont exceed this number
NDefines.NReligion.MIN_CARDINALS = 0											-- Least amount of cardinals/ Starting cardinals
NDefines.NReligion.MAX_CARDINALS = 0											-- Max amount of cardinals
NDefines.NReligion.MAX_CARDINALS_PER_COUNTRY = 0								-- Max cardinals in a single country
NDefines.NReligion.YEARLY_PAPAL_INFLUENCE_CATHOLIC = 1						-- The amount of yearly papal influence you receive each year for being catholic
NDefines.NReligion.MAX_PAPAL_INFLUENCE = 500.0								-- The maximum stored amount of papal influence for each country.
NDefines.NReligion.NUMBER_OF_POSSIBLE_CARDINALS = 0							-- Number of cardinals from said number of most successful provinces to be randomly picked from.
NDefines.NNationDesigner.MANDATE_SUBCONTINENT_NAME = "west_coast_superregion" -- Name of the subcontinent where the Mandate will be given to the biggest nation by development when using random generated nations
NDefines.NGovernment.RUSSIAN_ABILITY_POOL_SIZE = 100
NDefines.NGovernment.RUSSIAN_ABILITY_OPRICHNINA_CHANGE = -0.5
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_WE_CHANGE = -5
NDefines.NGovernment.RUSSIAN_ABILITY_STRELTSY_SPAWN_SIZE = 0.1
NDefines.NGovernment.SEIZE_CLERICAL_HOLDINGS_COST = 100
NDefines.NGovernment.INVITE_MINORITIES_COST = 100
NDefines.NGovernment.SANCTION_HOLY_WAR_COST = 100
NDefines.NGovernment.MAMLUK_ABILITY_POOL_SIZE = 100
NDefines.NGovernment.MAMLUK_RECRUIT_MANPOWER_MULTIPLIER = 100
NDefines.NGovernment.MAMLUK_SELL_SLAVES_DUCATS_MULTIPLIER = 10
NDefines.NGovernment.PROMOTE_MAMLUK_CULTURE_DURATION_YEARS = 5
NDefines.NGovernment.TRAIN_HORSEMANSHIP_DURATION_YEARS = 5
NDefines.NGovernment.CONSCRIPT_FROM_TRIBES_AMOUNT = 5
NDefines.NGovernment.TRIBAL_FEDERATION_ABILITY_COST = 50
NDefines.NGovernment.ENLIST_GENERAL_TRADITION = 50
NDefines.NGovernment.LEGACY_NATIVES_REFORM_REPUBLIC_SPONSOR = "republic_legacy"
NDefines.NGovernment.LEGACY_NATIVES_REFORM_MONARCHY_SPONSOR = "settlement_legacy"
NDefines.NGovernment.LEGACY_NATIVES_REFORM_THEOCRACY_SPONSOR = "theocracy_legacy"

